### PR TITLE
add timeout option in request part of "to yield response"

### PR DESCRIPTION
**Pull request by gustavnikolaj**
As discussed in #1 

After talking to @sunesimonsen I opted to change the name from within to timeout.

### CODE REVIEW

**Comment by papandreou** [comment]
Great, thanks! Could you release a new version yourself? I added you an an owner of the npm package.

**Comment by gustavnikolaj** [comment]
Released in v4.3.0 https://github.com/unexpectedjs/unexpected-http/commit/1cc452ab7f650561e0aa679c3d229b4e953f5b2a

And backported to v3 branch and released as v3.3.0 https://github.com/unexpectedjs/unexpected-http/commit/89326a045512b7d53735320d9b4d22b67672d3a8

Unfortunately I only realized that I needed to backport it after releasing v4.3.0, so if you go `npm install --save-dev unexpected-http@latest` you'd get v3.3.0 now.

**Comment by papandreou** [comment]
Remember to set the `tag` property in package.json when creating a legacy branch, eg.:

```
  "tag": "v3"
```

That'll prevent publications from updating the `latest` tag.

**Comment by gustavnikolaj** [comment]
Thanks! I was not aware of that. I guess the best I can do now is to release a 4.3.1 by now.

**Comment by papandreou** [comment]
There's also some weird `npm ...` command, but releasing a new version is also fine.

**Pull request merged**
